### ISSUE TITLE
Babel error caused when importing into a project that uses Babel.

### ISSUE THREAD

**Issue by ryardley** [marmelab/restful.js#15]
I am getting the following error when attempting to use restful.js in my project:

```bash
/Users/rudi/teg/teg-isomorphic-prototype/node_modules/restful.js/dist/restful.min.js:1
function(t,n,e){(function(t){"use strict";if(t._babelPolyfill)throw new Error(
                                                                    ^
Error: only one instance of babel/polyfill is allowed
    at Object.<anonymous> (/Users/rudi/teg/teg-isomorphic-prototype/node_modules/restful.js/dist/restful.min.js:1:8164)
    at Object.<anonymous> (/Users/rudi/teg/teg-isomorphic-prototype/node_modules/restful.js/dist/restful.min.js:1:8258)
    at n (/Users/rudi/teg/teg-isomorphic-prototype/node_modules/restful.js/dist/restful.min.js:1:383)
    at Object.t (/Users/rudi/teg/teg-isomorphic-prototype/node_modules/restful.js/dist/restful.min.js:1:4083)
    at n (/Users/rudi/teg/teg-isomorphic-prototype/node_modules/restful.js/dist/restful.min.js:1:383)
    at Object.<anonymous> (/Users/rudi/teg/teg-isomorphic-prototype/node_modules/restful.js/dist/restful.min.js:1:1186)
    at n (/Users/rudi/teg/teg-isomorphic-prototype/node_modules/restful.js/dist/restful.min.js:1:383)
    at e.baseUrl (/Users/rudi/teg/teg-isomorphic-prototype/node_modules/restful.js/dist/restful.min.js:1:470)
    at /Users/rudi/teg/teg-isomorphic-prototype/node_modules/restful.js/dist/restful.min.js:1:475
    at e.(anonymous function).exports (/Users/rudi/teg/teg-isomorphic-prototype/node_modules/restful.js/dist/restful.min.js:1:143)
```

I am creating an ES6 React application using Babel to handle the transpiling. 

I noticed in the Babel docs it specifically suggests that one doesn't use Babel in a library for this exact reason so I thought I would try to bring it to your attention.

https://babeljs.io/docs/using-babel/#require-hook

Cheers,
Rudi

**Comment by RobinBressan** [comment]
Hi,

Thanks for the report. I have to find a way not use the babel polyfill (already saw the same issue), I will dig into it when I get some time.

But still weird that the polyfill is not smart enough to handle this case.
