### ISSUE TITLE
fails on fresh npm install

### ISSUE THREAD

**Issue by clemsos** [marmelab/restful.js#39]
I just got an undefined error on a fresh install ( i tried ```0.7.0```, ```0.6.0``` and ```0.6.2```)

```
clemsos@clemsos $ npm install restful.js --save
npm WARN package.json xxx@0.0.1 No repository field.
npm http GET https://registry.npmjs.org/restful.js
npm http 304 https://registry.npmjs.org/restful.js
restful.js@0.7.0 node_modules/restful.js
clemsos@clemsos  $ node js/app.js   

/home/clemsos/Dev/superfeedr/client/node_modules/restful.js/dist/restful.min.js:8
&"10"===n[2]&&(e=o),function(){e(v)}}function p(){return function(){$(v)}}func
                                                                    ^
TypeError: undefined is not a function
    at /home/clemsos/Dev/superfeedr/client/node_modules/restful.js/dist/restful.min.js:8:433
    at f (/home/clemsos/Dev/superfeedr/client/node_modules/restful.js/dist/restful.min.js:8:233)
    at X.then (/home/clemsos/Dev/superfeedr/client/node_modules/restful.js/dist/restful.min.js:8:5711)
    at a (/home/clemsos/Dev/superfeedr/client/node_modules/restful.js/dist/restful.min.js:1:8505)
    at Function.e.request (/home/clemsos/Dev/superfeedr/client/node_modules/restful.js/dist/restful.min.js:8:8074)
    at Function.a.getAll (/home/clemsos/Dev/superfeedr/client/node_modules/restful.js/dist/restful.min.js:1:3989)
    at Function.l.getAll (/home/clemsos/Dev/superfeedr/client/node_modules/restful.js/dist/restful.min.js:1:2496)
    at Object.<anonymous> (/home/clemsos/Dev/superfeedr/client/js/app.js:11:46)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

my (very basic) app.js

```
var restful = require('restful.js');
var api = restful("localhost", 8080)
var articlesCollection = api.all('trending').getAll()
```

**Comment by clemsos** [comment]
ok, I finally made it work by updating node (and nvm) to be able to use es6 import with the ```--harmony``` flag. JS... you should always keep up the front !
